language: elixir

elixir:
  - 1.7.3
otp_release: 20.0


addons:
  postgresql: '9.5'

services:
  - postgresql

before_script:
  # - PGPASSWORD=postgres psql -c 'create database gigalixir_getting_started_test;' -U postgres

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  # - git remote add gigalixir https://smartdevbr01%40gmail.com:13642e76-fc5c-4b7d-bf0c-0718e4ae7359@git.gigalixir.com/darkseagreen-lightslateblue-peregrinefalcon.git
  # - mix test && git push -f gigalixir HEAD:refs/heads/master
  - mix test

